### ISSUE TITLE
passwords cannot have exclamation marks

### ISSUE THREAD

**Issue by vbojko** [f5devcentral/f5-cli#2]
I tried to configure my password, but it is not accepted if it includes and exclamation mark
use this schema:
***
f5 config auth create --authentication-provider bigip --name bigip-2
    --host 192.0.2.11 --user myuser --password mypassword --set-default
***
if I set password to something like "Pass!word" it will fail

**Comment by shyawnkarim** [comment]
When it fails do you get an error message that said it failed or do you get a message saying that it was successful? If the message is that it was successful, is the password just not applied to the BIG-IP when you go to test?

**Comment by kreynoldsf5** [comment]
@vbojko 

That's just a 'bashism' -- you can't have an unescaped ``!`` in a bash command (as it is used for history expansion). 

```shell
bash-5.0# f5 config auth create --authentication-provider bigip --name bigip-2 --host 192.0.2.11 --user myuser --password Test\!password--set-default
{
    "message": "Authentication configured successfully"
}
bash-5.0# f5 config auth create --authentication-provider bigip --name bigip-3 --host 192.0.2.11 --user myuser --password 'Test!password' --set-default
{
    "message": "Authentication configured successfully"
}
bash-5.0# /bin/sh
/f5-cli # f5 config auth create --authentication-provider bigip --name bigip-4 --host 192.0.2.11 --user myuser --password Test!password --set-default
{
    "message": "Authentication configured successfully"
}
```

**Comment by shyawnkarim** [comment]
@kreynoldsf5 thanks for that clarity.

Closing this issue since it has been answered.
